# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'github' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'Tabman', '2.12'
  pod 'SnapKit', '5.0.0'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'Alamofire', '5.5'
  pod 'Kingfisher', '6.3.1'
  use_frameworks!

  # Pods for github

  target 'githubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'githubUITests' do
    # Pods for testing
  end

end
